version: '3.5'

services:
  songkick-shoutouts:
    container_name: songkick-shoutouts
    build: ./
    volumes:
      - './:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '8080:3000'
    environment:
      - NODE_ENV=development